# Generated by Django 5.1.3 on 2024-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Хирургия - передовая область клиники HappyLifes'),
            preserve_default=False,
        ),
    ]
