# Generated by Django 5.1.3 on 2024-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_timeslot_week_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'newsletter follower',
                'verbose_name_plural': 'newsletter followers',
            },
        ),
    ]
